# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import content_audit_service_pb2 as content__audit__service__pb2


class ContentAuditServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Filter = channel.unary_unary(
                '/content_audit_service.ContentAuditService/Filter',
                request_serializer=content__audit__service__pb2.ContentAuditRequest.SerializeToString,
                response_deserializer=content__audit__service__pb2.ContentAuditResponse.FromString,
                )


class ContentAuditServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Filter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentAuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Filter': grpc.unary_unary_rpc_method_handler(
                    servicer.Filter,
                    request_deserializer=content__audit__service__pb2.ContentAuditRequest.FromString,
                    response_serializer=content__audit__service__pb2.ContentAuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'content_audit_service.ContentAuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContentAuditService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Filter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/content_audit_service.ContentAuditService/Filter',
            content__audit__service__pb2.ContentAuditRequest.SerializeToString,
            content__audit__service__pb2.ContentAuditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
