# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import infra_object_storage_service_pb2 as infra__object__storage__service__pb2


class InfraObjectStorageServiceStub(object):
    """clang-format off 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBuckets = channel.unary_unary(
                '/infra_object_storage_service.InfraObjectStorageService/ListBuckets',
                request_serializer=infra__object__storage__service__pb2.ListBucketsRequest.SerializeToString,
                response_deserializer=infra__object__storage__service__pb2.ListBucketsResponse.FromString,
                )
        self.GetSignedUploadLink = channel.unary_unary(
                '/infra_object_storage_service.InfraObjectStorageService/GetSignedUploadLink',
                request_serializer=infra__object__storage__service__pb2.GetSignedUploadLinkRequest.SerializeToString,
                response_deserializer=infra__object__storage__service__pb2.GetSignedUploadLinkResponse.FromString,
                )


class InfraObjectStorageServiceServicer(object):
    """clang-format off 
    """

    def ListBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignedUploadLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfraObjectStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBuckets,
                    request_deserializer=infra__object__storage__service__pb2.ListBucketsRequest.FromString,
                    response_serializer=infra__object__storage__service__pb2.ListBucketsResponse.SerializeToString,
            ),
            'GetSignedUploadLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignedUploadLink,
                    request_deserializer=infra__object__storage__service__pb2.GetSignedUploadLinkRequest.FromString,
                    response_serializer=infra__object__storage__service__pb2.GetSignedUploadLinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infra_object_storage_service.InfraObjectStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InfraObjectStorageService(object):
    """clang-format off 
    """

    @staticmethod
    def ListBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/infra_object_storage_service.InfraObjectStorageService/ListBuckets',
            infra__object__storage__service__pb2.ListBucketsRequest.SerializeToString,
            infra__object__storage__service__pb2.ListBucketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSignedUploadLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/infra_object_storage_service.InfraObjectStorageService/GetSignedUploadLink',
            infra__object__storage__service__pb2.GetSignedUploadLinkRequest.SerializeToString,
            infra__object__storage__service__pb2.GetSignedUploadLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
