# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infra-object-storage-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"infra-object-storage-service.proto\x12\x1cinfra_object_storage_service\"\x14\n\x12ListBucketsRequest\"&\n\x13ListBucketsResponse\x12\x0f\n\x07\x62uckets\x18\x01 \x03(\t\"1\n\x1aGetSignedUploadLinkRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\"\xe6\x01\n\x1bGetSignedUploadLinkResponse\x12\x13\n\x0brequest_uri\x18\x01 \x01(\t\x12\x66\n\x0frequest_headers\x18\x02 \x03(\x0b\x32M.infra_object_storage_service.GetSignedUploadLinkResponse.RequestHeadersEntry\x12\x13\n\x0bobject_name\x18\x03 \x01(\t\x1a\x35\n\x13RequestHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa0\x02\n\x19InfraObjectStorageService\x12t\n\x0bListBuckets\x12\x30.infra_object_storage_service.ListBucketsRequest\x1a\x31.infra_object_storage_service.ListBucketsResponse\"\x00\x12\x8c\x01\n\x13GetSignedUploadLink\x12\x38.infra_object_storage_service.GetSignedUploadLinkRequest\x1a\x39.infra_object_storage_service.GetSignedUploadLinkResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infra_object_storage_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _GETSIGNEDUPLOADLINKRESPONSE_REQUESTHEADERSENTRY._options = None
  _GETSIGNEDUPLOADLINKRESPONSE_REQUESTHEADERSENTRY._serialized_options = b'8\001'
  _globals['_LISTBUCKETSREQUEST']._serialized_start=68
  _globals['_LISTBUCKETSREQUEST']._serialized_end=88
  _globals['_LISTBUCKETSRESPONSE']._serialized_start=90
  _globals['_LISTBUCKETSRESPONSE']._serialized_end=128
  _globals['_GETSIGNEDUPLOADLINKREQUEST']._serialized_start=130
  _globals['_GETSIGNEDUPLOADLINKREQUEST']._serialized_end=179
  _globals['_GETSIGNEDUPLOADLINKRESPONSE']._serialized_start=182
  _globals['_GETSIGNEDUPLOADLINKRESPONSE']._serialized_end=412
  _globals['_GETSIGNEDUPLOADLINKRESPONSE_REQUESTHEADERSENTRY']._serialized_start=359
  _globals['_GETSIGNEDUPLOADLINKRESPONSE_REQUESTHEADERSENTRY']._serialized_end=412
  _globals['_INFRAOBJECTSTORAGESERVICE']._serialized_start=415
  _globals['_INFRAOBJECTSTORAGESERVICE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
