# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: url-shorten-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19url-shorten-service.proto\x12\x13url_shorten_service\")\n\x11ShortenUrlRequest\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t\"2\n\x12ShortenUrlResponse\x12\x1c\n\x14shortened_url_suffix\x18\x01 \x01(\t\"1\n\x11RestoreUrlRequest\x12\x1c\n\x14shortened_url_suffix\x18\x01 \x01(\t\"*\n\x12RestoreUrlResponse\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t2\xd5\x01\n\x11UrlShortenService\x12_\n\nShortenUrl\x12&.url_shorten_service.ShortenUrlRequest\x1a\'.url_shorten_service.ShortenUrlResponse\"\x00\x12_\n\nRestoreUrl\x12&.url_shorten_service.RestoreUrlRequest\x1a\'.url_shorten_service.RestoreUrlResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'url_shorten_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SHORTENURLREQUEST']._serialized_start=50
  _globals['_SHORTENURLREQUEST']._serialized_end=91
  _globals['_SHORTENURLRESPONSE']._serialized_start=93
  _globals['_SHORTENURLRESPONSE']._serialized_end=143
  _globals['_RESTOREURLREQUEST']._serialized_start=145
  _globals['_RESTOREURLREQUEST']._serialized_end=194
  _globals['_RESTOREURLRESPONSE']._serialized_start=196
  _globals['_RESTOREURLRESPONSE']._serialized_end=238
  _globals['_URLSHORTENSERVICE']._serialized_start=241
  _globals['_URLSHORTENSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
